// Code generated by "stringer -type=LEDEvent"; DO NOT EDIT.

package eventcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LED_NUML-0]
	_ = x[LED_CAPSL-1]
	_ = x[LED_SCROLLL-2]
	_ = x[LED_COMPOSE-3]
	_ = x[LED_KANA-4]
	_ = x[LED_SLEEP-5]
	_ = x[LED_SUSPEND-6]
	_ = x[LED_MUTE-7]
	_ = x[LED_MISC-8]
	_ = x[LED_MAIL-9]
	_ = x[LED_CHARGING-10]
	_ = x[LED_MAX-15]
	_ = x[LED_CNT-16]
}

const (
	_LEDEvent_name_0 = "LED_NUMLLED_CAPSLLED_SCROLLLLED_COMPOSELED_KANALED_SLEEPLED_SUSPENDLED_MUTELED_MISCLED_MAILLED_CHARGING"
	_LEDEvent_name_1 = "LED_MAXLED_CNT"
)

var (
	_LEDEvent_index_0 = [...]uint8{0, 8, 17, 28, 39, 47, 56, 67, 75, 83, 91, 103}
	_LEDEvent_index_1 = [...]uint8{0, 7, 14}
)

func (i LEDEvent) String() string {
	switch {
	case 0 <= i && i <= 10:
		return _LEDEvent_name_0[_LEDEvent_index_0[i]:_LEDEvent_index_0[i+1]]
	case 15 <= i && i <= 16:
		i -= 15
		return _LEDEvent_name_1[_LEDEvent_index_1[i]:_LEDEvent_index_1[i+1]]
	default:
		return "LEDEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
