// Code generated by "stringer -type=MiscEvent"; DO NOT EDIT.

package eventcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MSC_SERIAL-0]
	_ = x[MSC_PULSELED-1]
	_ = x[MSC_GESTURE-2]
	_ = x[MSC_RAW-3]
	_ = x[MSC_SCAN-4]
	_ = x[MSC_TIMESTAMP-5]
	_ = x[MSC_MAX-7]
	_ = x[MSC_CNT-8]
}

const (
	_MiscEvent_name_0 = "MSC_SERIALMSC_PULSELEDMSC_GESTUREMSC_RAWMSC_SCANMSC_TIMESTAMP"
	_MiscEvent_name_1 = "MSC_MAXMSC_CNT"
)

var (
	_MiscEvent_index_0 = [...]uint8{0, 10, 22, 33, 40, 48, 61}
	_MiscEvent_index_1 = [...]uint8{0, 7, 14}
)

func (i MiscEvent) String() string {
	switch {
	case 0 <= i && i <= 5:
		return _MiscEvent_name_0[_MiscEvent_index_0[i]:_MiscEvent_index_0[i+1]]
	case 7 <= i && i <= 8:
		i -= 7
		return _MiscEvent_name_1[_MiscEvent_index_1[i]:_MiscEvent_index_1[i+1]]
	default:
		return "MiscEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
