// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: config.proto

package config

import (
	keycode "github.com/erdichen/chromekey/evdev/keycode"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeymapEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From keycode.Code `protobuf:"varint,1,opt,name=from,proto3,enum=keycode.Code" json:"from,omitempty"`
	To   keycode.Code `protobuf:"varint,2,opt,name=to,proto3,enum=keycode.Code" json:"to,omitempty"`
}

func (x *KeymapEntry) Reset() {
	*x = KeymapEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeymapEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeymapEntry) ProtoMessage() {}

func (x *KeymapEntry) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeymapEntry.ProtoReflect.Descriptor instead.
func (*KeymapEntry) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *KeymapEntry) GetFrom() keycode.Code {
	if x != nil {
		return x.From
	}
	return keycode.Code(0)
}

func (x *KeymapEntry) GetTo() keycode.Code {
	if x != nil {
		return x.To
	}
	return keycode.Code(0)
}

type KeymapConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FnEnabled   bool           `protobuf:"varint,1,opt,name=fn_enabled,json=fnEnabled,proto3" json:"fn_enabled,omitempty"`
	FnKey       keycode.Code   `protobuf:"varint,2,opt,name=fn_key,json=fnKey,proto3,enum=keycode.Code" json:"fn_key,omitempty"`
	KeyMap      []*KeymapEntry `protobuf:"bytes,3,rep,name=key_map,json=keyMap,proto3" json:"key_map,omitempty"`
	ShiftKeyMap []*KeymapEntry `protobuf:"bytes,4,rep,name=shift_key_map,json=shiftKeyMap,proto3" json:"shift_key_map,omitempty"`
	UseLed      *keycode.LED   `protobuf:"varint,5,opt,name=use_led,json=useLed,proto3,enum=keycode.LED,oneof" json:"use_led,omitempty"`
}

func (x *KeymapConfig) Reset() {
	*x = KeymapConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeymapConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeymapConfig) ProtoMessage() {}

func (x *KeymapConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeymapConfig.ProtoReflect.Descriptor instead.
func (*KeymapConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *KeymapConfig) GetFnEnabled() bool {
	if x != nil {
		return x.FnEnabled
	}
	return false
}

func (x *KeymapConfig) GetFnKey() keycode.Code {
	if x != nil {
		return x.FnKey
	}
	return keycode.Code(0)
}

func (x *KeymapConfig) GetKeyMap() []*KeymapEntry {
	if x != nil {
		return x.KeyMap
	}
	return nil
}

func (x *KeymapConfig) GetShiftKeyMap() []*KeymapEntry {
	if x != nil {
		return x.ShiftKeyMap
	}
	return nil
}

func (x *KeymapConfig) GetUseLed() keycode.LED {
	if x != nil && x.UseLed != nil {
		return *x.UseLed
	}
	return keycode.LED(0)
}

var File_config_proto protoreflect.FileDescriptor

var file_config_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x1b, 0x65, 0x76, 0x64, 0x65, 0x76, 0x2f, 0x6b, 0x65,
	0x79, 0x63, 0x6f, 0x64, 0x65, 0x2f, 0x6b, 0x65, 0x79, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x0b, 0x4b, 0x65, 0x79, 0x6d, 0x61, 0x70, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x21, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0d, 0x2e, 0x6b, 0x65, 0x79, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x1d, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0d, 0x2e, 0x6b, 0x65, 0x79, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x02, 0x74, 0x6f, 0x22, 0xf2, 0x01, 0x0a, 0x0c, 0x4b, 0x65, 0x79, 0x6d, 0x61, 0x70, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x6e, 0x5f, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x66, 0x6e, 0x45, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x12, 0x24, 0x0a, 0x06, 0x66, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x6b, 0x65, 0x79, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x05, 0x66, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x07, 0x6b, 0x65,
	0x79, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x4b, 0x65, 0x79, 0x6d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x06, 0x6b, 0x65, 0x79, 0x4d, 0x61, 0x70, 0x12, 0x37, 0x0a, 0x0d, 0x73, 0x68, 0x69, 0x66,
	0x74, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x4b, 0x65, 0x79, 0x6d, 0x61, 0x70, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x73, 0x68, 0x69, 0x66, 0x74, 0x4b, 0x65, 0x79, 0x4d, 0x61,
	0x70, 0x12, 0x2a, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x5f, 0x6c, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x6b, 0x65, 0x79, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x4c, 0x45, 0x44,
	0x48, 0x00, 0x52, 0x06, 0x75, 0x73, 0x65, 0x4c, 0x65, 0x64, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a,
	0x08, 0x5f, 0x75, 0x73, 0x65, 0x5f, 0x6c, 0x65, 0x64, 0x42, 0x20, 0x5a, 0x1e, 0x65, 0x72, 0x64,
	0x69, 0x2e, 0x75, 0x73, 0x2f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x6b, 0x65, 0x79, 0x2f, 0x72,
	0x65, 0x6d, 0x61, 0x70, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData = file_config_proto_rawDesc
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_config_proto_rawDescData)
	})
	return file_config_proto_rawDescData
}

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_config_proto_goTypes = []interface{}{
	(*KeymapEntry)(nil),  // 0: config.KeymapEntry
	(*KeymapConfig)(nil), // 1: config.KeymapConfig
	(keycode.Code)(0),    // 2: keycode.Code
	(keycode.LED)(0),     // 3: keycode.LED
}
var file_config_proto_depIdxs = []int32{
	2, // 0: config.KeymapEntry.from:type_name -> keycode.Code
	2, // 1: config.KeymapEntry.to:type_name -> keycode.Code
	2, // 2: config.KeymapConfig.fn_key:type_name -> keycode.Code
	0, // 3: config.KeymapConfig.key_map:type_name -> config.KeymapEntry
	0, // 4: config.KeymapConfig.shift_key_map:type_name -> config.KeymapEntry
	3, // 5: config.KeymapConfig.use_led:type_name -> keycode.LED
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeymapEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeymapConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_config_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_rawDesc = nil
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
