package testdefs

/*
#include <linux/uinput.h>
*/
import "C"

const (
	UINPUT_IOCTL_BASE = C.UINPUT_IOCTL_BASE

	UI_SET_EVBIT   = C.UI_SET_EVBIT
	UI_SET_KEYBIT  = C.UI_SET_KEYBIT
	UI_SET_RELBIT  = C.UI_SET_RELBIT
	UI_SET_ABSBIT  = C.UI_SET_ABSBIT
	UI_SET_MSCBIT  = C.UI_SET_MSCBIT
	UI_SET_LEDBIT  = C.UI_SET_LEDBIT
	UI_SET_SNDBIT  = C.UI_SET_SNDBIT
	UI_SET_FFBIT   = C.UI_SET_FFBIT
	UI_SET_PHYS    = C.UI_SET_PHYS
	UI_SET_SWBIT   = C.UI_SET_SWBIT
	UI_SET_PROPBIT = C.UI_SET_PROPBIT
)
